services:
  redis:
    container_name: test_redis
    image: redis
    ports: 
      - 6379:6379
  app:
    container_name: test_app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 80:8000
    restart: always
    depends_on:
      - redis
  celery_app:
    container_name: test_celery_app
    build: .
    command: celery -A celery_app worker --pool=solo --loglevel=info
    depends_on:
      - redis
      - app